# Generated by Django 4.2.20 on 2025-04-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SPBU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=100)),
                ('jumlah_nozzle', models.IntegerField()),
                ('jumlah_pu_bbm', models.IntegerField()),
                ('tanggal_pengujian', models.DateField()),
                ('jenis_layanan', models.CharField(max_length=20)),
            ],
        ),
    ]
