# Generated by Django 4.2.20 on 2025-04-09 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spbu_app', '0002_stikerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StikerTera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_nozzle', models.PositiveIntegerField()),
                ('jumlah_pu_bbm', models.PositiveIntegerField()),
                ('tanggal_pengujian', models.DateField()),
                ('jenis_layanan', models.CharField(choices=[('Tahunan', 'Tera Ulang Tahunan'), ('Tambahan', 'Tera Tambahan')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='StikerData',
        ),
        migrations.RemoveField(
            model_name='spbu',
            name='jenis_layanan',
        ),
        migrations.RemoveField(
            model_name='spbu',
            name='jumlah_nozzle',
        ),
        migrations.RemoveField(
            model_name='spbu',
            name='jumlah_pu_bbm',
        ),
        migrations.RemoveField(
            model_name='spbu',
            name='tanggal_pengujian',
        ),
        migrations.AlterField(
            model_name='spbu',
            name='nama_perusahaan',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='stikertera',
            name='spbu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spbu_app.spbu'),
        ),
    ]
