# Generated by Django 5.2 on 2025-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spbu_app', '0004_rename_nama_perusahaan_spbu_spbu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stikertera',
            name='kategori',
            field=models.IntegerField(choices=[(1, 'Kategori 1'), (2, 'Kategori 2'), (3, 'Kategori 3'), (4, 'Kategori 4')], default=1),
            preserve_default=False,
        ),
    ]
