# Generated by Django 5.2 on 2025-04-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spbu_app', '0003_stikertera_delete_stikerdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spbu',
            old_name='nama_perusahaan',
            new_name='spbu',
        ),
        migrations.RenameField(
            model_name='stikertera',
            old_name='jumlah_nozzle',
            new_name='nozzle',
        ),
        migrations.RenameField(
            model_name='stikertera',
            old_name='jumlah_pu_bbm',
            new_name='pu_bbm',
        ),
    ]
